#!/bin/bash

if [ $# == 1 ] && [ $1 == "-h" ]
then
    echo "capillaroscopy_report.sh - Automatic generation of capillaroscopy reports" "\n"
    echo "This script will generate a plain text report (report.txt) from all"
    echo "capillaroscopy report PDFs in the current working directory." "\n"
    echo "usage: capillaroscopy_report.sh     (generate report)"
    echo "   (This assumes that the 'pdftotext' command is available in your PATH.)"
    echo "       capillaroscopy_report.sh -c  (generate report, then clean up the"
    echo "                                    text files that pdftotext generated)"
    echo "       capillaroscopy_report.sh -t  (generate report from text files"
    echo "                                              pre-generated by pdftotext)"
    echo "       capillaroscopy_report.sh -h  (shows this help)"
    exit
fi

# Generate report
PDFs=*.pdf

output="report.txt"

for f in $PDFs; do
    echo "Processing $f..."
    bn=`basename -s ".pdf" "$f"`
    if [ "$1" != "-t" ] && [ "$1" != "--fromtext" ]; then
        pdftotext -layout "$f" >> "$bn".txt
    fi
    awk -f capillaroscopy_report.awk "$bn".txt >> $output
    if [ "$1" = "-c" ] || [ "$1" = "--cleanup" ]; then
        echo "Deleting $bn.txt..."
        rm $bn.txt
    fi
    echo "     **********     " >> $output
done